# Generated by Django 4.2.1 on 2023-06-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_country_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
    ]
